### ISSUE TITLE
1.10 update omitted version change in install.xml

### ISSUE THREAD

**Issue by PaulWebster** [LMS-Community/plugin-DSDPlayer#5]
Not sure if this should have been a manual change or the github action should have done it ... but the change to maxversion to support LMS 9 changed the repo version to 1.10 but not the install.xml version so it fails LMS installation.

(wrote this from iOS github client that does not seem to provide a way to add comment to change)

**Comment by Brown-Sound** [comment]
Yes, also discovered this update this morning. It is supposed to go from v1.09 to v1.10 but it never does and keeps re-asking for an update. I even tried to remove the original v1.09 plugin, restart LMS, then re-add the plugin, but it just re-adds v1.09. I guess I'll just ignore the update notice for now. Oh, and email address is not usable from the plugin page.

**Comment by ralph-irving** [comment]
Thanks Paul.
I've merge PR#6 and created release 1.11
version and maxVersion tags in install.xml file look correct now.
